In [5]:
import requests
import pandas as pd

In [61]:
def airport_data():

    location = input('Insert location:')
    print()

    url = "https://aerodatabox.p.rapidapi.com/airports/search/term"
    querystring = {"q":location.lower(), "limit":"10"}

    response = requests.get(url, headers=headers, params=querystring)

    return response.json()

def airport_code():
    response = airport_data()
    code = response["items"][0]["iata"]
    return code

def flight_distance_time(from_, to_):
    url = f"https://aerodatabox.p.rapidapi.com/airports/iata/{from_}/distance-time/{to_}"
    response = requests.get(url, headers=headers)
    return pd.json_normalize(response.json()).T

In [62]:
print('[DEPARTURE]')
from_ = airport_code()
print('[DESTINATION]')
to_ = airport_code()

flight_df = flight_distance_time(from_, to_)
flight_df

[DEPARTURE]
Insert location:amsterdam

[DESTINATION]
Insert location:munich

                                            0
approxFlightTime                     01:00:00
from.icao                                EHAM
from.iata                                 AMS
from.name                  Amsterdam Schiphol
from.shortName                       Schiphol
from.municipalityName               Amsterdam
from.location.lat                     52.3086
from.location.lon                    4.763889
from.countryCode                           NL
to.icao                                  EDDM
to.iata                                   MUC
to.name                               Munich
to.shortName                           Munich
to.municipalityName                    Munich
to.location.lat                       48.3538
to.location.lon                       11.7861
to.countryCode                             DE
greatCircleDistance.meter           665432.86
greatCircleDistance.km                 665.43
greatCircleDistance.mile               413.48
greatCircleDistance.nm                  359.3
greatCircleDistance.feet           2183178.67